Sync vscode extension install commands

diff --git a/install b/install
--- a/install
+++ b/install
@@ -29,6 +29,21 @@ if [ ! -f $home_dir/.gitconfig ]; then
  	cp $dotfiles_dir/git/.gitconfig ~/
 fi
 
+if ! [ -x "$(command -v code)" ]
+then
+  echo 'Error: VSCode CLI is not installed.' >&2
+else
+  # Generated by code --list-extensions | xargs -L 1 echo code --install-extension
+  code --install-extension eamodio.gitlens
+  code --install-extension ehaynes99.vscode-select-same-text
+  code --install-extension Equinusocio.vsc-community-material-theme
+  code --install-extension Equinusocio.vsc-material-theme
+  code --install-extension equinusocio.vsc-material-theme-icons
+  code --install-extension extr0py.vscode-relative-line-numbers
+  code --install-extension sleistner.vscode-fileutils
+  code --install-extension vscodevim.vim
+fi
+
 if [ ! -f $home_dir/Library/Application\ Support/Code/User/settings.json ]; then
   echo "Linking VSCode config - settings.json"
   ln -s $dotfiles_dir/vscode/settings.json $home_dir/Library/Application\ Support/Code/User/settings.json
